
#ifndef _AUTO_VERSION_INFORMATION_H_
#define _AUTO_VERSION_INFORMATION_H_

#define SM_BUILD_TAG	 	""
#define SM_BUILD_UNIQUEID	"0:fcdef8474873" SM_BUILD_TAG
#define SM_VERSION			"1.0.0"
#define SM_FULL_VERSION		SM_VERSION SM_BUILD_TAG
#define SM_FILE_VERSION		1,0,0,0

#endif /* _AUTO_VERSION_INFORMATION_H_ */

