name: Cache
on:
  workflow_call:
    outputs:
      key:
        value: ${{ jobs.cache.outputs.key }}
      dir:
        value: .cache

jobs:
  cache:
    name: Create cache
    runs-on: ubuntu-latest
    outputs:
      key: ${{ steps.cache-key.outputs.key }}

    env:
      SOURCEMOD_REF: '2e229b111534b1be007dc3bd9acfcf2fc472e893'
      AMBUILD_REF: '9ed1920068c8a767ae78022102abc93a6822eaad'
    steps:
      - name: Create cache key
        id: cache-key
        run: echo "key=sourcemod-${SOURCEMOD_REF}-ambuild-${AMBUILD_REF}" >> $GITHUB_OUTPUT

      - name: Retrieve the cache
        id: cache
        uses: actions/cache@v6
        with:
          path: .cache
          key: ${{ steps.cache-key.outputs.key }}
          enableCrossOsArchive: true
          lookup-only: true

      - uses: actions/checkout@v7
        if: ${{ !steps.cache.outputs.cache-hit }}
        name: SourceMod checkout
        with:
          repository: alliedmodders/sourcemod
          ref: ${{ env.SOURCEMOD_REF }}
          submodules: recursive
          path: .cache/sourcemod
          persist-credentials: false

      - uses: actions/checkout@v7
        if: ${{ !steps.cache.outputs.cache-hit }}
        name: AMBuild checkout
        with:
          repository: alliedmodders/ambuild
          ref: ${{ env.AMBUILD_REF }}
          path: .cache/ambuild
          persist-credentials: false
