name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - overhaul
  
  push:
    branches:
      - master
      - overhaul

jobs:
  cache:
    uses: ./.github/workflows/cache.yml
  
  build:
    name: Build
    needs: cache

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-22.04', 'ubuntu-latest', 'windows-2019', 'windows-latest' ]
        include:
        # we need to ship ubuntu 22.04 because of glibc reasons
          - os: ubuntu-22.04
            #cc: clang-8
            #cxx: clang++-8
            cc: clang
            cxx: clang++
            upload: true
            upload-artifact-name: accelerator_linux
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
            upload: false
            upload-artifact-name: none
          - os: windows-2019
            cc: msvc
            cxx: msvc
            upload: false
            upload-artifact-name: none
          - os: windows-latest
            cc: msvc
            cxx: msvc
            upload: true
            upload-artifact-name: accelerator_windows
    
    uses: ./.github/workflows/build-extension.yml
    with:
      os: ${{ matrix.os }}
      cc: ${{ matrix.cc }}
      cxx: ${{ matrix.cxx }}
      upload: ${{ matrix.upload }}
      upload-artifact-name: ${{ matrix.upload-artifact-name }}
      cache-key: ${{ needs.cache.outputs.key }}
      cache-dir: ${{ needs.cache.outputs.dir }}
