name: CI
on:
  workflow_dispatch:
  workflow_call:

jobs:
  sm112:
    name: SM 1.12
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang-22
            cxx: clang++-22
            container: 'ghcr.io/alliedmodders/build-containers/debian11-clang22:latest'
            artifact: accelerator_sm112_linux
          - os: windows-latest
            cc: msvc
            cxx: msvc
            container: ''
            artifact: accelerator_sm112_windows
    uses: ./.github/workflows/build-extension.yml
    with:
      os: ${{ matrix.os }}
      cc: ${{ matrix.cc }}
      cxx: ${{ matrix.cxx }}
      container: ${{ matrix.container }}
      sourcemod-branch: '1.12-dev'
      upload: true
      upload-artifact-name: ${{ matrix.artifact }}

  sm113:
    name: SM 1.13
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            cc: clang-22
            cxx: clang++-22
            container: 'ghcr.io/alliedmodders/build-containers/debian11-clang22:latest'
            artifact: accelerator_sm113_linux
          - os: windows-latest
            cc: msvc
            cxx: msvc
            container: ''
            artifact: accelerator_sm113_windows
    uses: ./.github/workflows/build-extension.yml
    with:
      os: ${{ matrix.os }}
      cc: ${{ matrix.cc }}
      cxx: ${{ matrix.cxx }}
      container: ${{ matrix.container }}
      sourcemod-branch: 'master'
      upload: true
      upload-artifact-name: ${{ matrix.artifact }}
